---
title: "R Notebook"
output: html_notebook
---

```{r pckg, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(dplyr)
library(tidyquant)
library(highcharter)
library(gt)
library(readr)
library(pbapply)
library(purrr)
```

## Summary of holdings
```{r holdings, message=FALSE, warning=FALSE, include=FALSE}

# Read data of lots defined in "holdings.csv" and creating "holdings" data frame
holdings <- read_csv("~/R_projects/mypotfolio/data/holdings.csv")

# Assinging today's date to any lots in the holdings data frame without a "sell_date"
fill_up <- today()
holdings$sell_date[is.na(holdings$sell_date)] <- as.Date(fill_up, format = "%Y%m%d")

# Preparing the holdings DF adding more colunms
holdings %>% 
  select(-sell_date) %>% 
  mutate(lot_value_at_buy = shares_hold * buy_price) %>% 
  arrange(buy_date) %>% 
  gt() %>% 
  tab_header(
    title = md("**Portfolio - Lots**")
  ) %>%
  cols_label(
    ticker = "Ticker",
    buy_date = "Date bought",
    shares_hold = "Shares",
    buy_price = "Price",
    lot_value_at_buy = "Value invested"
  ) %>% 
   tab_source_note(
    source_note = md("**Source:** holdings.csv")
   ) %>% 
  fmt_date(
    columns = vars(buy_date),
    date_style = 13
  ) %>%
  fmt_currency(
    columns = vars(buy_price, lot_value_at_buy),
    currency = "USD"
  )

# Getting quotes for each lot in the porfolio
df <- get_quotes("~/R_projects/mypotfolio/data/holdings.csv")

# Defining a unique id for each lot
ids <- unique(df$lot_ID)

gl_min <- min(df$gain_loss)
gl_max <- max(df$gain_loss)
glp_min <- min(df$gl_pct)
glp_max <- max(df$gl_pct)

```

## First Lot
```{r lot_1, echo=FALSE, message=FALSE, warning=FALSE}

# Creating charts for each lot

dfx <- df %>% 
  group_by(date) %>% 
  summarise(pl = sum(gain_loss)) 

dfx %>% 
  gt() %>% 
   tab_header(
    title = paste("Profit & Loss in USD")
  ) %>%
  fmt_date(
    columns = vars(date),
    date_style = 13
  ) %>%
  fmt_currency(
    columns = vars(pl),
    currency = "USD"
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold",
                      color = "green"),
    locations = cells_body(
      columns = vars(pl),
      rows = pl == max(dfx$pl))
    ) %>% 
  cols_label(
    date = "Date",
    pl = "P/L"
  )

dfx %>% 
  highcharter::hchart(showInLegend = FALSE,
                        type = "areaspline",
                        highcharter::hcaes(x = date, y = pl),
                        marker = list(enabled = FALSE),
                        color = "#4B5463",
                        fillColor = "#5FA147",
                        negativeFillColor = "#CC3D2D",
                        fillOpacity = 0.4) %>%
    highcharter::hc_tooltip(useHTML = TRUE,
                            headerFormat = "",
                            pointFormat = "{point.symbol} <br>
                            Date: {point.date} <br>
                            P/L: {point.pl}",
                            borderWidth = 1,
                            borderColor = "#000000") %>%
    highcharter::hc_add_theme(hc_theme_smpl()) %>%
    highcharter::hc_xAxis(title = list(text = "Date")) %>%              # X axis definition
    highcharter::hc_yAxis(title = list(text = "P&L")) %>%         # Y axis definition
    highcharter::hc_credits(enabled = TRUE,                             # add credits
                            text = "Source: Yahoo Financial, through `tidyquant`package")
```

